version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    environment:
      - NODE_ENV=development

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server/src:/app/src
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:password@db:5432/mycows_rfi

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mycows_rfi
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: